export const SUCCESS_SUFFIX = "_SUCCESS";
export const FAIL_SUFFIX = "_FAIL";

export const FETCH_HOME = "FETCH_HOME";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_CART_COUNT = "FETCH_CART_COUNT";
export const APP_SETTINGS = "APP_SETTINGS";
export const ADD_WISHLIST = "ADD_WISHLIST";
export const DELETE_WISHLIST = "DELETE_WISHLIST";

export const HOME_LAYOUT = "HOME_LAYOUT";
export const USER = "USER";
export const LOGOUT = "LOGOUT";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_BILLING = "UPDATE_BILLING";
export const UPDATE_SHIPPING = "UPDATE_SHIPPING";
export const SAVE_NOTIFICATION = "SAVE_NOTIFICATION";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";
