export const SUCCESS_SUFFIX = "_SUCCESS";
export const FAIL_SUFFIX = "_FAIL";

export const FETCH_HOME = "FETCH_HOME";
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_CART_COUNT = "FETCH_CART_COUNT";
export const APP_SETTINGS = "APP_SETTINGS";
export const ADD_WISHLIST = "ADD_WISHLIST";
export const DELETE_WISHLIST = "DELETE_WISHLIST";

export const HOME_LAYOUT = "HOME_LAYOUT";
export const USER = "USER";
export const LOGOUT = "LOGOUT";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_BILLING = "UPDATE_BILLING";
export const UPDATE_SHIPPING = "UPDATE_SHIPPING";
export const SAVE_NOTIFICATION = "SAVE_NOTIFICATION";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";

export const SAVE_SHIPPING = "SAVE_SHIPPING";
export const CHANGE_SHIPPING_COUNTRY = "CHANGE_SHIPPING_COUNTRY";
export const CHANGE_SHIPPING_STATE = "CHANGE_SHIPPING_STATE";
export const CHANGE_SHIPPING_CITY = "CHANGE_SHIPPING_CITY";
export const CHANGE_SHIPPING_PINCODE = "CHANGE_SHIPPING_PINCODE";
export const CLEAR_CART_COUNT = "CLEAR_CART_COUNT";
export const DELETE_ITEM_CART = "DELETE_ITEM_CART";
export const FILTER_CATEGORY = "FILTER_CATEGORY";
