export const SUCCESS_SUFFIX = '_SUCCESS';
export const FAIL_SUFFIX = '_FAIL';

export const FETCH_HOME = 'FETCH_HOME';
export const FETCH_CATEGORIES = "FETCH_CATEGORIES";
export const FETCH_CART_COUNT = "FETCH_CART_COUNT";
export const APP_SETTINGS = 'APP_SETTINGS';
export const ADD_WISHLIST = "ADD_WISHLIST";
export const DELETE_WISHLIST = "DELETE_WISHLIST";